# Allergologie

## Anwendungen

Pollenius ist eine Anwendung für Mobiltelefone, entwickelt von der Charité – Universitätsmedizin Berlin, die Berliner Allergikern nahezu in Echtzeit Daten zum Pollenflug liefert. Mit einer Verzögerung von nur etwa drei Stunden zeigt die App, basierend auf Messungen einer automatisierten Pollenfalle auf dem Tempelhofer Feld, die Konzentrationen der acht allergierelevantesten Pflanzen wie Birke, Gräser oder Ambrosia. Nutzer können zudem ein Symptomtagebuch führen, das Pollenkonzentration, Beschwerden und Medikamenteneinnahme übersichtlich darstellt, um Diagnose und Therapie zu unterstützen. Verfügbar für Android und iOS, sammelt Pollenius anonymisierte Daten, um die Versorgungsforschung zu Pollenallergien voranzutreiben und individuelle Vorhersagemodelle zu entwickeln. [play.google.com](https://play.google.com/store/apps/details?id=com.tpsproduction.pollenius) [apps.apple.com](https://apps.apple.com/eg/app/pollenius/id6502574737)

Die [Pollen-App](https://www.pollenstiftung.de/pollenvorhersage/pollenapps.html) der Pollenstiftung ist ein kostenloser mobiler Dienst für Allergiker in Deutschland, Österreich, Frankreich, Schweiz, Schweden, Spanien, Großbritannien und Südtirol, verfügbar für iOS und Android. Sie liefert Echtzeit-Vorhersagen zur Pollenbelastung basierend auf der Postleitzahl des Nutzers und erstellt nach Eingabe individueller Allergiesymptome eine personalisierte Belastungsvorhersage. Mit Funktionen wie einem Allergie-Selbsttest, einem persönlichen Pollentagebuch zur Dokumentation und Weiterleitung an Ärzte im PDF-Format sowie einem Erinnerungsservice für Therapieplanung unterstützt die App Allergiker, ihre Beschwerden gezielt zu managen und die Pollensaison besser zu bewältigen.

## Pollenfluginformationdienst

Der [Pollenflug-Gefahrenindex](https://www.dwd.de/DE/leistungen/gefahrenindizespollen/gefahrenindexpollen.html) des Deutschen Wetterdienstes (DWD) ist ein Online-Echtzeit-Informationsdienst, der tägliche Vorhersagen zur Pollenbelastung für die acht allergologisch wichtigsten Pollenarten in Deutschland (Hasel, Erle, Esche, Birke, Süßgräser, Roggen, Beifuß und Ambrosia) bereitstellt. Die Vorhersagen geben die Pollenkonzentration (Pollen pro m³ Luft) für den aktuellen und die zwei folgenden Tage an, was Allergikern hilft, ihre Aktivitäten und Medikamenteneinnahme gezielt anzupassen.

Die Studie „Automatisches Pollenmonitoring in Deutschland“ von Buters et al. (Allergo J. 2020) hebt die Bedeutung des elektronischen Polleninformationsnetzwerks (ePIN) hervor, insbesondere in Bayern, wo acht automatische Pollenmonitore die Grundlage für Echtzeit-Pollendaten bilden. Diese Monitore, nutzen Bilderkennung, um Pollen mit einer Erkennungsrate von etwa 91 % zu identifizieren, und liefern Daten, die direkt online über Plattformen wie epin.bayern.de verfügbar sind. Die Studie betont, dass solche Systeme Allergikern sofortige Informationen über lokale Pollenkonzentrationen bieten, was eine schnelle Korrelation zwischen Symptomen und Pollenbelastung ermöglicht. Dies ist besonders in Zeiten von Atemwegserkrankungen wie COVID-19 hilfreich, um Allergien von viralen Infektionen zu unterscheiden. [@buters2021automatisches]
