# Dermatologie

## Einleitung

Digitale Hautanalyse-Tools unterscheiden sich in der Präzision der Analyse, der Benutzerfreundlichkeit, den unterstützten Plattformen (App vs. Web), der Kostenstruktur (kostenlos vs. kostenpflichtig) und der Spezialisierung auf bestimmte Hautprobleme oder -typen. Während einige Tools eher auf eine schnelle, allgemeine Hautanalyse abzielen, konzentrieren sich andere auf tiefgehende Untersuchungen, die von Dermatologen oder Hautpflegeexperten unterstützt werden. 

[hautnetz-deutschland.de](https://hautnetz-deutschland.de/) ist ein Netzwerk für dermatologische Versorgung, das Patienten den Zugang zu spezialisierten Hautärzten und telemedizinischen Dienstleistungen in Deutschland erleichtert.

[www.gemeinsam-gegen-hautkrebs.de](https://www.gemeinsam-gegen-hautkrebs.de/) informiert über Hautkrebsprävention, Früherkennung und Behandlungsmöglichkeiten und fördert die Zusammenarbeit zwischen Patienten, Ärzten und Organisationen im Kampf gegen Hautkrebs.

## Softwarelösungen

| Product                  | Company                  | URL                                                                 |
|--------------------------|--------------------------|---------------------------------------------------------------------|
| Skinive                  | Skinive Holding BV       | [skinive.com](https://skinive.com/de/for-specialists/)              |
| intellimago              | zollsoft GmbH            | [intellimago.de](https://intellimago.de)                            |

: Übersicht Softwarelösungen Business-to-Business

| Product                  | Company                  | URL                                                                 |
|--------------------------|--------------------------|---------------------------------------------------------------------|
| Nia Neurodermitis       | Nia Health GmbH          | [nia-health.de](https://www.nia-health.de/)                         |
| IQONIC.AI                | SkinTech Corp. GmbH      | [iqonic.ai](https://www.iqonic.ai/de)                               |
| SkinScreener App         | medaia GmbH              | [skinscreener.com](https://skinscreener.com)                        |
| derma2go                 | derma2go AG              | [derma2go.com](https://www.derma2go.com)                             |
| DermaValue                | DermaValue GmbH          | [dermavalue.com](https://www.dermavalue.com/de/)                    |
| SkinTheory               | SkinTheory               | [apps.apple.com/us/app/skintheory-skin-acne-routine](https://apps.apple.com/us/app/skintheory-skin-acne-routine/id1490049787) |
| Miiskin                  | Miiskin                  | [miiskin.com](https://miiskin.com/)                                  |
| SkinTheory (Android)     | SkinTheory               | [com.skintheory.skintheory](https://play.google.com/store/apps/details?id=com.skintheory.skintheory&pli=1) |
| MDacne                   | MDacne                   | [mdacne.com](https://www.mdacne.com/)                                |
| La Roche-Posay Effaclar SpotScan | La Roche-Posay      | [effaclar-spotscan](https://www.larocheposay.de/event/effaclar-spotscan) |
| AI-Derm                  | IAC Search and Media Europe, Ltd. | [ai-derm.com](https://ai-derm.com/)                                 |
| CRUSE Control            | UCARE (Urticaria Centers of Reference and Excellence) | [cruse-control.com](https://cruse-control.com/) |

: Übersicht Softwarelösungen Direct-to-Consumer

Die [ItchyMonsters-App](https://www.itchy-monsters.de/) unterstützt Kinder mit Neurodermitis spielerisch bei der täglichen Hautpflege. Durch Gamification und Augmented Reality motiviert die App Kinder dazu, regelmäßig einzucremen, während ein integriertes Hauttagebuch Eltern und Ärzt:innen hilft, den Therapieverlauf zu überwachen. Kostenlos und werbefrei bietet sie eine kindgerechte, stressfreie Lösung zur Verbesserung der Hautgesundheit.

## Digitale Wissensplattformen

[DermNetNZ](https://dermnetnz.org/) ist eine internationale Dermatologie-Websplattform mit Millionen jährlichen Lesern und mehr als 2500 Hautthemen sowie 25.000 klinischen Bildern. Sie bietet umfassende, leicht verständliche und von Dermatologen überprüfte Informationen zu Hauterkrankungen, und Behandlungen, darunter Themen wie Akne, Psoriasis und Hautkrebs. Es gibt weitere Funktionen wie Haut-Checker, Videos, einem Ressourcenzentrum und DermNet PRO für Fachkräfte.

## Forschung

| Product                  | Company                  | URL                                                                 |
|--------------------------|--------------------------|---------------------------------------------------------------------|
| AcneDet on Roboflow      | AcneDet                  | [roboflow.com/acnedet/acnedet-v1](https://universe.roboflow.com/acnedet/acnedet-v1) |
| Derm.AI                  | Fraunhofer AICOS         | [dermai.projects.fraunhofer.pt](http://dermai.projects.fraunhofer.pt/index.html) |
| KIADEKU | KIADEKU GmbH | [interaktive-technologien.de/projekte/kiadeku](https://www.interaktive-technologien.de/projekte/kiadeku) |

: Übersicht Forschungsprojekte

[Aisencia](https://aisencia.de/) ist ein Start-up aus Bremen, das sich auf KI-gestützte Lösungen für die Dermatopathologie spezialisiert hat. Mit der Software Vistaneos optimiert das Unternehmen den Workflow in Laboren, indem es ein Bildverwaltungssystem mit künstlicher Intelligenz kombiniert, um präzise und schnelle Diagnosen von Hautkrankheiten wie Basalzellkarzinom oder Melanom zu ermöglichen. Aisencia hat Auszeichnungen erhalten, darunter den 2. Platz beim EXIST Start-up Award 2024 und den 1. Platz beim CAMPUSiDEEN-Wettbewerb 2023.
