# Diätologie

## Soziale Medien

Die Deutsche Gesellschaft für Ernährung e. V. (DGE) bietet auf ihrem YouTube-Kanal ["dge_wissen"](https://www.youtube.com/@dge_wissen) wissenschaftlich fundierte Informationen zu Ernährungsthemen. Das Angebot umfasst unter anderem Podcasts wie „Wie wollen wir essen?“, Videos zu den lebensmittelbezogenen Ernährungsempfehlungen sowie Beiträge zur Ernährung in verschiedenen Lebensphasen. Ziel ist es, Verbraucher*innen, Fachkräfte und Entscheidungsträger*innen evidenzbasiert über aktuelle Erkenntnisse der Ernährungswissenschaft zu informieren. Neben dem Kanal der Deutschen Gesellschaft für Ernährung e. V. (DGE), der wissenschaftlich fundierte Informationen zu allgemeinen Ernährungsthemen bietet, stellt der YouTube-Kanal ["ines2023videos"](https://www.youtube.com/@ines2023videos) der Medizinischen Universität Graz praxisnahe Inhalte zur Ernährung im Alter bereit. Die Videoserie richtet sich insbesondere an Betreuungspersonen und Pflegekräfte und vermittelt alltagsnahe Tipps zur gesunden Ernährung älterer Menschen.
