# Qualitätsmanagement

## KBV-PraxisCheck

Der [KBV-PraxisCheck](https://www.kbv.de/html/mein_praxischeck.php) ist ein kostenloses Online-Tool der Kassenärztlichen Bundesvereinigung (KBV), das speziell für Ärzte, Psychotherapeuten und Praxisteams entwickelt wurde. Mit diesem Selbsttest können Praxen ihre Qualität und Sicherheit in verschiedenen Bereichen wie Hygiene, Impfen, Prävention von Wundinfektionen, Datenschutz, Informationssicherheit, Patientensicherheit und Qualitätsmanagement überprüfen. Anhand von Fragen, die in wenigen Minuten beantwortet werden können, erhält die Praxis sofort Rückmeldungen zu ihren Leistungen und praktische Tipps zur Verbesserung der Praxisabläufe.

## KTQ-Zertifizierung (Kooperation für Transparenz und Qualität im Gesundheitswesen)

[KTQ](https://ktq.de/) bietet ein Zertifizierungssystem speziell für Arzt- und Zahnarztpraxen sowie psychotherapeutische Praxen und Medizinische Versorgungszentren (MVZ). Es umfasst Selbst- und Fremdbewertung und zielt darauf ab, Qualitätsmanagement-Systeme zu entwickeln und zu verbessern.

## DIN EN ISO 9001:2015

Diese internationale Norm für Qualitätsmanagement kann von Praxen angewendet werden, um ihre Qualitätssysteme zu zertifizieren. Sie legt den Fokus auf Kundenzufriedenheit durch eine effektive Qualitätsverwaltung.

## QM-Richtlinie des Gemeinsamen Bundesausschusses (G-BA)

Diese Richtlinie schreibt ein internes Qualitätsmanagement für Vertragsärzte und -psychotherapeuten vor. Zertifizierungen basierend auf dieser Richtlinie sind nicht zwingend erforderlich, aber Praxen können sich nachweisen lassen, dass sie den Anforderungen entsprechen.

## Übersicht QM Software

| Software         | Anbieter                          | URL                | Anmerkungen                                                                                   |
|:-----------------|:----------------------------------|:-------------------|:-----------------------------------------------------------------------------------------------|
| Paul             | Paul Solutions GmbH               | [paul-solutions.de](https://paul-solutions.de)  | 30 Tage kostenlos, dann min 69Euro / Monat                                              |
| vismed QM        | vismed GmbH                       | [vismed.de](https://vismed.de)          | mehr als nur Wissensmanagement                                                            |
| neoQM            | neoQM GmbH                        | [neoqm.de](https://neoqm.de)           | für alle möglichen Branchen auch für Arztpraxen                                         |
| RoxTra           | RoxTra GmbH                       | [roxtra.com](https://roxtra.com)         |                                                     |
| OrgaVision       | OrgaVision GmbH                   | [orgavision.com](https://orgavision.com)     | für mehrere Branchen und auch für Arztpraxen. Kosten bei 25 MitarbeiterInnen pro Jahr 2900 Euro (mon 241,67 Euro) |
| BITqms           | BITWORKS EDV-Dienstleistungs-GmbH | [bitworks.net](https://bitworks.net)       | vorwiegend Krankenhäuser                                                           |
| ConSense         | ConSense GmbH                     | [consense-gmbh.de](https://consense-gmbh.de)   | vorwiegend Krankenhäuser                                                          |
| Latz Protect     | Latz Protect GmbH                 | [latz-protect.com](https://www.latz-protect.com)       | für Arztpraxen                                                                    |
| Intralean Medical | Intralean GmbH | [intralean-medical.de](https://www.intralean-medical.de/) |                                                                                                |

: Übersicht Softwarelösungen Qualitätsmanagement Praxis

| Software         | Anbieter                          | URL                | Anmerkungen                                                                                   |
|:-----------------|:----------------------------------|:-------------------|:-----------------------------------------------------------------------------------------------|
| eQMS             | Page-Tec GmbH                     | [page-tec.de](https://page-tec.de)        | formal auch für Gesundheitswesen, aber eher für andere Unternehmen            |
| i:solution CAQ   | i:select GmbH                     | [concept-pro.de](https://www.concept-pro.de/qm-software/)        | mehr als nur QM aber nicht spezifisch für das Gesundheitswesen        |
| CWA SmartProcess | CAQ AG Factory Systems            | [caq.de](https://caq.de)             | zwar für Medizintechnik und Labor aber nicht für Medizin                               |
| eQMS             | Page-Tec GmbH                     | [eqms.de](https://eqms.de)            | QM für viele Branchen ua. Medizintechnik und Labor, keine Praxen          |
| SimplifyU        | SimplifyU GmbH                    | [simplifyu.de](https://simplifyu.de)       | 100% auf Akut- und Rehaeinrichtungen                                                |
| QM-Pilot         | QM-Pilot GmbH                     | [qm-pilot.de](https://qm-pilot.de)        | schweizer Firma, man kann Flusschemata entwerfen um Prozesse zu beschreiben..     |
| Q.wiki           | Q.wiki GmbH                       | [q-wiki.de](https://q-wiki.de)          | QM für Unternehmen und nicht für das Gesundheitswesen                                  |
| BabtecQ          | Babtec Informationssysteme GmbH   | [babtec.de](https://babtec.de)          | Für Elektronik Maschinenbau, Automotive... nur MedTechnik, keine Arztpraxen            |
| WissIntra NG     | Wissensmanagement GmbH            | [wissintra.dbeyond.group/de](https://wissintra.dbeyond.group/de/)       | nicht für das Gesundheitswesen                    |
| Testify          | Testify GmbH                      | [testify.io](https://testify.io)         | nicht für das Gesundheitswesen                                                       |
| iqs CAQ          | iqs Software GmbH                 | [iqs.de](https://iqs.de)             | nicht für das Gesundheitswesen                                                       |
| SmartProcess     | CWA GmbH                          | [cwa-software.com](https://cwa-software.com)   | nicht für das Gesundheitswesen                                                                 |
| MS LDS           | MS Management Systeme GmbH        | [msqf-gmbh.de](https://msqf-gmbh.de)       | nicht für das Gesundheitswesen                                                                        |

: Übersicht Softwarelösungen allgemeines Qualitätsmanagement

| Software         | Anbieter                          | URL                | Anmerkungen                                                                                   |
|:-----------------|:----------------------------------|:-------------------|:-----------------------------------------------------------------------------------------------|
| Schedura         | ablida GmbH                       | [schedura.de](https://www.schedura.de/de) | Künstliche Intelligenz für die Dokumentenverwaltung                         |
| QM-Assist        | social-software.de                | [social-software.de](https://social-software.de) | Softwarekatalog für die Sozialwirtschaft      |

: Weitere Softwarelösungen
