# Rheumatologie

Das [Rhadar-Projekt](https://rhadar.de/de/) (RheumaDatenRheport GbR) ist ein Netzwerk zur Verbesserung der rheumatologischen Versorgung in Deutschland. Angesichts des Mangels an Rheumatologen vernetzt Rhadar Patienten schnell mit Fachärzten, um frühzeitige Diagnosen und Therapien zu ermöglichen. Durch digitale Tools wie RhePort und RheCORD unterstützt es Patienten bei der Eigenüberwachung und Ärzte bei der Behandlungsanpassung, während administrative Aufgaben minimiert werden, um den Fokus auf die Patientenversorgung zu legen.

## Software

Software in der Rheumatologie zeichnet sich durch spezifische Funktionen wie Anamneseerhebung, Dokumentation von Krankheitsverläufen und Scoring-Systeme für die Bewertung von Krankheitsaktivität aus. 

| Product                  | Company                         | URL                                   |
|--------------------------|---------------------------------|---------------------------------------|
| RheDAT                   | EMIL Software GmbH              | [rhedat.de/](http://www.rhedat.de/) |
| RheMIT                   | EMIL Software GmbH              | [bdrh-service.de/rhemit/](https://www.bdrh-service.de/rhemit/) |
| RheCORD                  | EMIL Software GmbH              | [rhecord.de/](https://www.rhecord.de/) |
| RhePort                  | Rheuma-Online GmbH              | [rheport.de/](https://www.rheport.de/) |
| Rheuma-VOR               | BDRh Service GmbH               | [rheuma-vor.de/](https://www.rheuma-vor.de/) |
| Joint-Pain-Assessment-Tool (JPAST) | -                          | -                                     |
| Bechterew-check.de       | Deutsche Vereinigung Morbus Bechterew e.V. | [bechterew-check.de](https://bechterew-check.de) |
| Digital Rheuma Lab       | -                               | [digitalrheumalab.de/](https://www.digitalrheumalab.de/) |
| Mida Rheuma® App         | MIDA GmbH                       | [midaia.de/](https://midaia.de/) |
| RheumaDok                | EMIL Software GmbH              | [rheumadok.de/](https://www.rheumadok.de/) |
| EMIL                     | EMIL Software GmbH              | [itc-ms.de/](https://www.itc-ms.de/) |
| DocuMed.rh               | -                               | -                                     |
| RheumaNet | Deutsche Gesellschaft für Rheumatologie e.V. | [rheumanet.org/](https://www.rheumanet.org/) |
| VivoCare Rheuma Assist| StatConsult GmbH         | [vivocare-software.de](https://www.vivocare-software.de)            |

: Übersicht Softwarelösungen Rheumatologie

## Digitalisierungsinitiative durch Fachgesellschaft

Das [Digital Rheumatology Network](https://digitalrheumatology.org/) vernetzt eine Reihe von Digitalisierungsinitiativen. Zu den Aktivitäten gehören der jährliche „Digital Rheumatology Day“, ein hybrides Event, das Experten aus Medizin, Forschung, Pharma, MedTech und Gesundheits-IT zusammenbringt, um neue digitale Praktiken wie digitale Therapeutika, Biomarker, künstliche Intelligenz und virtuelle Realität zu diskutieren. Die Plattform bietet zudem Webinare und Podcasts, die Themen wie digitale Versorgungspfade und Fernüberwachung fokussieren, sowie einen Blog mit aktuellen Entwicklungen. Der „Digital Rheumatology Research Award“ zeichnet innovative Forschungsarbeiten aus, etwa zur Nutzung von Smartphone-Apps für Patientenberichte oder KI in der Diagnostik.

Der Artikel „Five years of the Digital Rheumatology Network: insights and future directions“ beschreibt die Entwicklung und Erfolge des Digital Rheumatology Network (DRN) in den letzten fünf Jahren. DRN hat sich als bedeutende Plattform etabliert, die digitale Innovationen in der Rheumatologie fördert und Fachleute aus Medizin, Technologie und Patienten zusammenbringt. Thematisch liegt der Fokus auf künstlicher Intelligenz, Fernüberwachung, digitalen Therapien und der Verbesserung elektronischer Patientenakten. Trotz großer Fortschritte bestehen noch Herausforderungen wie mangelnde Dateninteroperabilität und begrenzte digitale Kompetenz. Zukünftig will DRN die digitale Transformation begleiten, die Zusammenarbeit stärken und die digitale Bildung weiter ausbauen. [@chan2025five]

### Umfrage der Kommission Digitale Rheumatologie 2020

Die [Kommission "Digitale Rheumatologie"](https://dgrh.de/Start/DGRh/Die-Gesellschaft/Kommissionen-Amtszeit-2023-2025/Kommission-Digitale-Rheumatologie.html)
 der Deutschen Gesellschaft für Rheumatologie (DGRh) konzentriert sich auf die Digitalisierung in der Rheumatologie. Ihre Aufgaben umfassen die Erarbeitung von Empfehlungen zur Nutzung digitaler Anwendungen und Technologien in der rheumatologischen Praxis, die Verbesserung der Patientenversorgung durch digitale Lösungen und die Förderung der Forschung in diesem Bereich. Diese Kommission spielt eine zentrale Rolle bei der Integration neuer digitaler Tools und Methoden zur Optimierung der Diagnose, Behandlung und Nachsorge von Patienten mit rheumatischen Erkrankungen.

Die Tabelle aus dem "Positionspapier der Kommission zur Nutzung digitaler Anwendungen in der Rheumatologie" der Deutschen Gesellschaft für Rheumatologie e.V. (DGRh) zeigt eine Auswahl von Apps, die für rheumatologische Zwecke nützlich sind und die Bewertungen im Rahmen einer Umfrage auf dem Rheumatologischen Kongress 2018.

| App Name             | Zweck                      | Anteil an App-Empfehlungen für Kollegen n=52, n (%) | Anteil an App-Empfehlungen für Patienten n=8, n (%) | Preis         | iOS | Android |
|----------------------|----------------------------|-----------------------------------------------------|-----------------------------------------------------|---------------|-----|---------|
| Labcal              | Berechnungstool           | 1 (2)                                              | X                                                   | Kostenlos     | Ja  | Nein    |
| Medcalx             | Berechnungstool           | 4 (8)                                              | X                                                   | Kostenlos     | Ja  | Nein    |
| PAH – Woche für Woche | Berechnungstool           | 1 (2)                                              | X                                                   | Kostenlos     | Ja  | Ja      |
| Calculate by QxMD   | Berechnungstool           | 4 (8)                                              | X                                                   | Kostenlos     | Ja  | Ja      |
| Rheuma helper       | Berechnungstool           | 7 (13)                                             | 1 (13)                                              | Kostenlos     | Ja  | Ja      |
| Ada                 | Diagnoseunterstützung      | 1 (2)                                              | 1 (13)                                              | Kostenlos     | Ja  | Ja      |
| Isabel              | Diagnoseunterstützung      | 1 (2)                                              | X                                                   | Kostenpflichtig | Nein | Nein    |
| AmiKo Desitin       | Medikamenteninformation   | 1 (2)                                              | X                                                   | Kostenlos     | Ja  | Ja      |
| Arznei aktuell      | Medikamenteninformation   | 11 (21)                                            | 1 (13)                                              | Kostenlos     | Ja  | Ja      |
| Arzneimittel Pocket | Medikamenteninformation   | 2 (4)                                              | X                                                   | Kostenlos     | Ja  | Ja      |
| Corticonverter      | Medikamenteninformation   | 1 (2)                                              | X                                                   | Kostenlos     | Nein | Nein    |
| EKO2go              | Medikamenteninformation   | 1 (2)                                              | X                                                   | Kostenlos     | Ja  | Ja      |
| Embryotox           | Medikamenteninformation   | 2 (4)                                              | 3 (38)                                              | Kostenlos     | Ja  | Ja      |
| Pneumotox           | Medikamenteninformation   | 1 (2)                                              | X                                                   | Kostenlos     | Nein | Nein    |
| RheumaLive          | Symptom-Tracking          | 2 (4)                                              | 2 (25)                                              | Kostenlos     | Ja  | Ja      |

: Befragungsergebnisse der DGRh

Quelle: [@knitza2020ziele]

## DiGAs in der Rheumatologie

Eine Studie von [@Albrecht2025] zeigt, dass digitale Gesundheitsanwendungen (DiGAs) eine Ergänzung zur Behandlung rheumatischer Erkrankungen darstellen, insbesondere bei der Symptomkontrolle von Rückenschmerzen und Gewichtsmanagement. Von 191 Patient:innen nutzten 66 % die DiGAs wöchentlich, 51 % berichteten von einer Symptomverbesserung, wobei Anwendungen wie Kaia Rückenschmerzen und Somnio besonders effektiv waren. Trotz hoher Benutzerfreundlichkeit bleibt die Abschlussrate niedrig (15 %), was auf die Notwendigkeit zusätzlicher Patientenschulungen und Unterstützungsangebote hinweist. Für Rheumatolog:innen bieten DiGAs eine Möglichkeit, Patienten über digitale Mittel individuell zu unterstützen und die Versorgung zu ergänzen.

## Patientenermächtigung

Die Anwendung [Lupus-Pass](https://lupus-rheumanet.org/forschung/der-lupus-pass/) der Lupus Erythematodes Selbsthilfegemeinschaft ermöglicht Betroffenen, ihre Krankheitsdaten zu verwalten und fördert durch ein Diskussionsforum den Austausch und die Gemeinschaftsbildung unter Lupus-Patienten. Neben der Präventionsunterstützung, wie der Einschätzung des Arteriosklerose-Risikos, bietet die Plattform auch wissenschaftliche Datenerhebung zur Verbesserung der Forschung und Lebensqualität. Zusätzlich dient sie als ständiger Begleiter, um Folgeerkrankungen vorzubeugen und persönliche Gesundheitsstrategien zu entwickeln.

Die digitale Anwendung [AbbVie Care](https://www.abbvie-care.de/), ist ein Beispiel für ein industriegetriggertes Serviceprogramm, das Patienten mit chronischen Erkrankungen unterstützt, die ein AbbVie-Medikament verschrieben bekommen haben. Diese Plattform bietet über digitale Technologien eine Vielzahl an Funktionen: Patienten können sich online anmelden und erhalten Zugang zu einem persönlichen Gesundheitscoach, der per Telefon oder Videoanruf individuelle Beratung und Unterstützung – etwa zur Medikamentenanwendung und Verabreichung – bietet. Zudem ermöglicht die App den Zugriff auf Informationsmaterial zu Erkrankungen, Tipps für den Alltag und einen Downloadbereich für Unterlagen. Als Weiterhin gibt es die Möglichkeit, eine mobile medizinische Fachkraft für Hausbesuche zu buchen, sowie eine Servicehotline für schnelle Hilfe, wodurch die Therapie digital begleitet und die Selbstverwaltung der Patienten gestärkt wird.

Die Webseite [LupusCheck.de](https://www.lupuscheck.de/) ist ein Informations- und Unterstützungsportal für Menschen mit Lupus erythematodes, ihre Angehörigen und Interessierte. Unter dem Motto „Mit Lupus leben – Wissen macht stark“ bietet sie Inhalte zu Themen wie Diagnose, Symptome, Therapie und Lebensführung, erstellt von Expertinnen und Experten sowie ergänzt durch Erfahrungsberichte von Betroffenen. Zu den Angeboten zählen Downloads wie Checklisten, Patientenbroschüren und Vorlagen, ebenso wie Mutmachgeschichten, Videos von digitalen Lupustagen und ein Podcast mit Fachinterviews. Die Plattform fördert den Austausch, klärt über den Umgang mit der chronischen Autoimmunerkrankung auf und unterstützt dabei, den Alltag mit Lupus besser zu bewältigen.

„MeinCarePlus“ (https://www.meincareplus.de/de_DE/home.html) ist eine von Biogen entwickelte digitale Plattform, die Patienten mit chronisch-entzündlichen Erkrankungen der Gelenke, des Darms, der Haut oder der Augen sowie deren Angehörigen Unterstützung bietet. Sie bietet Informationen zu Diagnosen, Therapien und Alltagsbewältigung, ergänzt durch praktische Tools wie die Care+ App für Therapiemanagement, einen Apothekenfinder und Download-Ressourcen wie Broschüren. Zusätzlich fördert die Plattform den Austausch durch Blogs, Podcasts und Erfahrungsberichte, um Betroffenen und deren Umfeld Wissen, Orientierung und Gemeinschaft zu vermitteln.

„Rheumafit“ (https://www.rheumafit.ch/) ist die erste Online-Plattform mit Übungsvideos für Menschen mit Morbus Bechterew und anderen rheumatischen Erkrankungen, entwickelt von der Schweizerischen Vereinigung Morbus Bechterew in Zusammenarbeit mit der Zürcher Hochschule für Angewandte Wissenschaften (ZHAW). Sie bietet über 20 speziell konzipierte Trainingsprogramme, die von Physiotherapeuten geleitet werden, inklusive Angaben zu Dauer, Intensität und trainierten Körperpartien, sowie Tipps für das Training zu Hause. Die Plattform passt Übungen an individuelle Einschränkungen an, ist auf jedem internetfähigen Gerät zugänglich und unterstützt Betroffene dabei, Kraft, Beweglichkeit und Koordination flexibel und selbstständig zu fördern. Eine kostenlose Registrierung ermöglicht vollen Zugriff auf alle Inhalte.

Das [Digitale Rheumatologische Informationssystem](https://dirhis.info/) (DiRhIS) der BDRh Service GmbH bietet Rheumatolog:innen eine kostenfreie, webbasierte Plattform, um Patient:innen maßgeschneiderte Informationspakete zu Diagnose, Therapie und Leben mit rheumatischen Erkrankungen bereitzustellen. Über eine Oberfläche können Ärzt:innen Inhalte wie Videos, Podcasts oder Dokumente aus einem validierten Contentangebot auswählen und personalisierte „Infokörbe“ erstellen, die Patient:innen per Link, QR-Code oder App erhalten. Die Inhalte, geprüft durch ein Expertengremium, sind leicht verständlich und können mit individuellem Branding versehen werden. DiRhIS ist mit RheDAT verknüpft und wird von Fachverbänden wie der Deutschen Rheuma-Liga unterstützt.

## Besondere Versorgungsmodelle

RheDAT ist ein zentrales Instrument zur Qualitätssicherung in der rheumatologischen Versorgung. Als Bestandteil von besonderen Versorgungsverträgen des BDRh wird eine gesonderte Vergütung bereitgestellt. Diese besonderen Versorgungsmodelle – wie *RheumaOne*, *ASV*, *KKH-RheCORD*, *VERhO* oder *PETRA 2.0* – bieten über die Regelversorgung hinausgehende Leistungen. Sie ermöglichen unter anderem eine intensivere Betreuung, neue Vergütungsstrukturen und innovative Versorgungskonzepte.

## Forschung

Das REMOTRA-Projekt (REMote moniToring in pReclinical Arthritis) ist eine Machbarkeitsstudie, die die frühzeitige Erkennung von rheumatoider Arthritis (RA) durch digitales Monitoring und patientenzentrierte Aufklärung fördert. In der prospektiven Kohortenstudie wurden 43 RA-Risikopersonen (65,9 % weiblich, Durchschnittsalter 50,1 Jahre) eingeschlossen, die nach dem Anschauen von Aufklärungsvideos zu Frühzeichen von RA und Gelenkselbstuntersuchung die REMOTRA-App nutzten. Die Studie zeigte hohe Patientenakzeptanz (NPS 54,4 für Aufklärungsvideo), gute Benutzbarkeit (SUS 88,1/100 nach 3 Monaten) und eine Adhärenz von 58,5 %. Mit einem negativen prädiktiven Wert und einer Sensitivität von 100 % konnte REMOTRA RA-Ausbruch zuverlässig ausschließen, jedoch war der positive prädiktive Wert niedrig (12 %). Die Ergebnisse unterstreichen das Potenzial digitaler Ansätze für die RA-Früherkennung, erfordern aber weitere Validierung in multizentrischen Studien. [@pfeuffer2025early]

Die Studie mit dem Titel „Remote monitoring or patient-initiated care in axial spondyloarthritis: a 3-armed randomised controlled noninferiority trial“ zielte darauf ab, zu bestimmen, ob neuartige Nachsorgeregime wie Fernüberwachung (remote monitoring) oder patienteninitiierte Versorgung einer üblichen Behandlung in der Aufrechterhaltung einer geringen Krankheitsaktivität bei Patienten mit axialer Spondyloarthritis (axSpA) nicht unterlegen sind. Diese randomisierte, kontrollierte, dreigliedrige, unverblindete Nicht-Unterlegenheitsstudie rekrutierte Patienten mit axSpA, die sich in geringer Krankheitsaktivität befanden und eine stabile Behandlung mit Tumornekrosefaktor-Inhibitoren erhielten. Die Ergebnisse zeigten, dass sowohl die Nachsorge mit Fernüberwachung als auch die patienteninitiierte Versorgung der üblichen Versorgung in der Aufrechterhaltung einer geringen Krankheitsaktivität nicht unterlegen waren. Darüber hinaus war die patienteninitiierte Versorgung die ressourcenschonendste Nachsorge für Gesundheitsdienstleister. [@berg2025remote]
