# Zahnärztliche Praxis

Zahnärztliche Software bietet eine Vielzahl von Funktionen. Dazu gehören Praxismanagement, das die Verwaltung von Terminen, Patientenakten und Abrechnungen umfasst, sowie Elektronische Gesundheitsakten. Moderne Programme bieten auch Telemedizinlösungen, E-Rezept-Funktionen und mobile Zugriffs-Optionen, um die Flexibilität und Effizienz in der Praxis zu erhöhen.

Zahnärztliche Software muss spezielle Anforderungen erfüllen, die sich von denen allgemeiner medizinischer Praxen unterscheiden. Dazu gehören detaillierte Zahndokumentationen wie Odontogramme für die Behandlung und Planung sowie die Integration von speziellen Bildgebungsverfahren wie intraorale und panoramische Röntgenaufnahmen. Diese Software muss auch Funktionen für die Planung von Prothesen und Kieferorthopädie und besondere Abrechnungscodes unterstützen, die nur in der Zahnmedizin verwendet werden. Darüber hinaus bieten sie oft Visualisierungen für Behandlungspläne und spezialisierte Systeme zur Patientenerinnerung, um die spezifischen Bedürfnisse und Abläufe in zahnärztlichen Praxen abzudecken.

- **Allgemeine Verwaltungsfunktionen:**
  - Terminplanung
  - Patientenregistrierung und -verwaltung
  - Kontaktmanagement

- **Abrechnung und Finanzmanagement:**
  - Handhabung von zahnärztlichen Abrechnungscodes
  - Zahlungsprozessierung
  - Finanzübersicht

- **Berichterstattung und Analyse:**
  - Praxiseinkommensberichte
  - Patientendemografie-Berichte

- **Patienteninformationen und klinische Verwaltung:**
  - Elektronische Gesundheitsakten mit Integration in andere Systeme (Interoperabilität)
  - Detallierte Zahndokumentation (Odontogramme)
  - Behandlungsplanung mit Visualisierungen

- **Bildgebungs-Integration:**
  - Verknüpfung mit Bildgebungssystemen

- **Kommunikation und Konnektivität:**
  - Interoperabilität mit Laboren, Apotheken und Krankenhäusern (Telematikinfrastruktur)
  - Telemedizin-Funktionen für Video-Sprechstunden
  - Mobile Zugriffsmöglichkeiten auf Patienten- und Praxisdaten

- **Spezialisierte zahnärztliche Funktionen:**
  - Integration mit Dental-Labors für Prothesen- und Kieferorthopädiearbeiten
  - Spezifische Abrechnungscodes für die Zahnmedizin
  - Patientenerinnerungssysteme für regelmäßige Kontrollen

|    | Software                     | URL                                                                                                                                        |
|---:|:-----------------------------|:-------------------------------------------------------------------------------------------------------------------------------------------|
|  0 | teemer                       | [ARZ.dent GmbH](http://www.teemer.de)                                                                                                      |
|  1 | VISIdent                     | [BDV GmbH](http://www.bdv.com)                                                                                                             |
|  2 | VISInext                     | [BDV GmbH](http://www.bdv.com)                                                                                                             |
|  3 | CAPAZ                        | [CAPAZ GmbH](http://www.capaz.de)                                                                                                          |
|  4 | CGM HIGHDENT PLUS            | [CompuGroup Medical Dentalsysteme GmbH](https://www.cgm.com/deu_de/produkte/zahnarztpraxis/cgm-highdent-plus.html)                         |
|  5 | CGM XDENT                    | [CompuGroup Medical Software GmbH](https://www.cgm.com/deu_de/lp/cgm-dentalsysteme/software-mit-cloud-cgm-xdent-fuer-zahnaerzt-innen.html) |
|  6 | ChreMaSoft                   | [CompuGroup Medical Dentalsysteme GmbH](http://www.cgm-dentalsysteme.de)                                                                   |
|  7 | Z1                           | [CompuGroup Medical Dentalsysteme GmbH](http://www.cgm-dentalsysteme.de)                                                                   |
|  8 | ZahnarztRechner              | [CompuGroup Medical Dentalsysteme GmbH](http://www.cgm-dentalsysteme.de)                                                                   |
|  9 | Dental Express/Ortho Express | [Computer Forum GmbH](http://www.dental-vision.de)                                                                                         |
| 10 | ivoris                       | [Computer konkret AG](http://www.computer-konkret.com)                                                                                     |
| 11 | INFINITY Q HEALTH            | [CROSSSOFT GmbH](http://www.crosssoft.de)                                                                                                  |
| 12 | D1                           | [D1 GmbH](http://www.D1.software)                                                                                                          |
| 13 | DS4                          | [DAMPSOFT GmbH](http://www.dampsoft.de)                                                                                                    |
| 14 | DS-WIN-PLUS                  | [DAMPSOFT GmbH](http://www.dampsoft.de)                                                                                                    |
| 15 | iSiDent                      | [DATEXT iT-Beratung](http://www.datext.de)                                                                                                 |
| 16 | DENSoffice                   | [DENS GmbH](http://www.dens-berlin.com)                                                                                                    |
| 17 | dentport                     | [Dentport GmbH](http://dentport.de)                                                                                                        |
| 18 | DentRechner                  | [DentRechner](http://www.dentrechner.de)                                                                                                   |
| 19 | ErgoDent                     | [ErgoDent Software GmbH](http://www.ergodent.de)                                                                                           |
| 20 | EVIDENT                      | [EVIDENT GmbH](http://www.evident.de)                                                                                                      |
| 21 | KFO-Office                   | [FDK Fachdienst der Kieferorthopäden GmbH & Co. KG](http://www.fdk-bremen.de)                                                              |
| 22 | PRAXIDENT A4                 | [h&k GbR](http://praxident.de)                                                                                                             |
| 23 | DENT-MAGIC                   | [h&k GbR](http://praxident.de)                                                                                                             |
| 24 | Orgadontic Office            | [Orgadontic](http://www.orgadontic.de)                                                                                                     |
| 25 | LinuDent                     | [PHARMATECHNIK GmbH & Co. KG](http://www.linudent.de)                                                                                      |
| 26 | apollonia / iDent            | [Procedia GmbH](http://www.procedia.de)                                                                                                    |
| 27 | charly by solutio            | [solutio GmbH & Co. KG](http://www.solutio.de)                                                                                             |
| 28 | DIOS ZX                      | [Spitta GmbH](http://www.dios.de)                                                                                                          |
| 29 | Pdent                        | [Winkler Software](http://www.winklersoft.com)                                                                                             |
| 30 | claire                       | [Patient 21 SE](http://www.zm-r.de/)                                                                                                       |
| 31 | tomedo DENTAL                | [zollsoft GmbH](https://zollsoft.de/)                                                                                                      |

: Übersicht Zahnarztsoftware

Quelle: [@KZBV_EDV_Statistik]

| Software                            | URL                                                               | Beschreibung |
|:------------------------------------|:-------------------------------------------------------------------|:------------|
| Athena                              | [Athena](https://www.athenahealth.com)                            | Eine Praxisverwaltungssoftware, die Terminplanung, Abrechnung und Patientenverwaltung umfasst. |
| Sonia                               | [Sonia](https://www.sonia-health.de)                              | Mit Sonia werden Aufklärung, Beratung und Behandlung in Ihrer Zahnarztpraxis automatisch einheitlich und vollständig dokumentiert. |

: Übersicht zahnärztliche Dokumentationswerkzeuge

[PraxiPal](https://www.praxipal.com/) ist ein in 2024 gegründetes Berliner Startup, das eine KI-gestützte virtuelle Rezeptionistin für Arztpraxen anbietet. Die Lösung automatisiert Telefonanrufe, entlastet das Praxispersonal und verbessert die Erreichbarkeit für Patienten.
