 on:
   workflow_dispatch:
   push:
     branches: main
    
 name: Quarto Publish
    
 jobs:
   build-deploy:
     runs-on: ubuntu-latest
     permissions:
       contents: write
     steps:
       - name: Check out repository
         uses: actions/checkout@v4
       - name: Set up Quarto
         uses: quarto-dev/quarto-actions/setup@v2
       - name: install tinytex
         run: quarto install tinytex
       - name: install dependencies
         run: pip install jupyter feedparser
       - name: Set QUARTO_PROFILE
         run: echo "QUARTO_PROFILE=dilob" >> $GITHUB_ENV
       - name: Render and Publish
         uses: quarto-dev/quarto-actions/publish@v2
         with:
           target: gh-pages
         env:
           GITHUB_TOKEN: $
